# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36315c7e0f106f3566d3da53925cc40bf5f85d577ec718ac080302293012e04b0255dcadd3bfbcfb7f72aaed9921b4a5e72e2ef8b8ac4a19c945bce431a905dc

test:
  secret_key_base: e2c498bd9234fea53922d029dc98af985d016abfdf187ec8cdb231bf91ed28c59ed3bad10ea797c0244b39cac1f83fdfe1c757ecf459812b7f45900c8f7faa7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
